# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'InterexyTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InterexyTest


pod 'Kingfisher'
pod 'Alamofire'

end
